target . delete ( "__TARGET__" ) 
if pc . count_item ( 31039 ) >= 1 and pc . count_item ( 31040 ) >= 1 then 
pc . remove_item ( 31039 , pc . count_item ( 31039 ) ) 
pc . remove_item ( 31040 , pc . count_item ( 31040 ) ) 
say_title ( mob_name ( 20378 ) ) 
say ( gameforge . main_quest_lv96 . _250_say ) 
say ( "" ) 
set_state ( "state2_4" ) 
else 
say_title ( mob_name ( 20378 ) ) 
say ( gameforge . main_quest_lv96 . _220_say ) 
say ( "" ) 
set_state ( "state2_2" ) 
end 
